apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-domain-com
  namespace: applications
spec:
  secretName: staging-domain-com-tls
  issuerRef:
    name: staging-issuer
    kind: Issuer
  commonName: staging.domain.com
  dnsNames:
  - staging.domain.com