apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-com
  namespace: applications
spec:
  secretName: domain-com-tls
  issuerRef:
    name: issuer
    kind: Issuer
  commonName: domain.com
  dnsNames:
  - domain.com