apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-pvc
  namespace: applications
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
